FROM openresty/openresty:1.13.6.1-2-alpine

RUN apk update

RUN apk add perl

RUN apk add net-tools

RUN apk add curl

RUN mkdir -p /work/logs /work/conf /work/conf/conf.d

RUN ln -s /usr/local/openresty/nginx/conf/mime.types /work/conf
